; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28106.4 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG124646 DB	'D:\Qt\Qt5.13.0\5.13.0\msvc2017_64\include\QtCore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG124647 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG124648 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_CollectData@@3Uqt_meta_stringdata_CollectData_t@@B DD 0ffffffffH ; qt_meta_stringdata_CollectData
	DD	0bH
	DD	00H
	ORG $+4
	DQ	0000000000000048H
	DD	0ffffffffH
	DD	0eH
	DD	00H
	ORG $+4
	DQ	000000000000003cH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000033H
	DB	043H
	DB	06fH
	DB	06cH
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	00H
	DB	063H
	DB	06fH
	DB	06cH
	DB	065H
	DB	065H
	DB	063H
	DB	074H
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	04eH
	DB	06fH
	DB	077H
	DB	00H
	DB	00H
	ORG $+4
$SG127044 DB	'invalid argument', 00H
	ORG $+7
?qt_meta_data_CollectData@@3QBIB DD 08H			; qt_meta_data_CollectData
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	00H
	DD	013H
	DD	02H
	DD	06H
	DD	02bH
	DD	00H
$SG127045 DB	'%s', 00H
	ORG $+1
$SG124985 DB	'D:\Qt\Qt5.13.0\5.13.0\msvc2017_64\include\QtCore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG127049 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG124986 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG124987 DB	'qRegisterNormalizedMetaType', 00H
$SG122061 DB	'%s', 00H
	ORG $+1
$SG125324 DB	'D:\Qt\Qt5.13.0\5.13.0\msvc2017_64\include\QtCore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG125325 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG125326 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG127046 DB	'D:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
$SG122060 DB	'containers incompatible for swap', 00H
	ORG $+7
$SG127047 DB	'D', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H, '8', 00H
	DB	'1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG127048 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG127762 DB	'D:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xlocale', 00H
$SG122064 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'P', 00H, 'o', 00H, 'c', 00H, 's', 00H, 00H, 00H
	ORG $+2
$SG122062 DB	'D:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
	ORG $+8
$SG122063 DB	'D', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H, '8', 00H
	DB	'1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG122065 DB	'"', 00H, 'c', 00H, 'o', 00H, 'n', 00H, 't', 00H, 'a', 00H
	DB	'i', 00H, 'n', 00H, 'e', 00H, 'r', 00H, 's', 00H, ' ', 00H, 'i'
	DB	00H, 'n', 00H, 'c', 00H, 'o', 00H, 'm', 00H, 'p', 00H, 'a', 00H
	DB	't', 00H, 'i', 00H, 'b', 00H, 'l', 00H, 'e', 00H, ' ', 00H, 'f'
	DB	00H, 'o', 00H, 'r', 00H, ' ', 00H, 's', 00H, 'w', 00H, 'a', 00H
	DB	'p', 00H, '"', 00H, 00H, 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@CollectData@@UEBAPEBUQMetaObject@@XZ ; CollectData::metaObject
PUBLIC	?qt_metacast@CollectData@@UEAAPEAXPEBD@Z	; CollectData::qt_metacast
PUBLIC	?qt_metacall@CollectData@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; CollectData::qt_metacall
PUBLIC	?qt_static_metacall@CollectData@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CollectData::qt_static_metacall
PUBLIC	?coleectDataNow@CollectData@@QEAAXXZ		; CollectData::coleectDataNow
PUBLIC	?staticMetaObject@CollectData@@2UQMetaObject@@B	; CollectData::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QThread@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QThread@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QThread@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@CollectData@@2UQMetaObject@@B DB 030H DUP (?) ; CollectData::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@CollectData@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@CollectData@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@CollectData@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@CollectData@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@CollectData@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+172
	DD	imagerel $unwind$?qt_metacall@CollectData@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@CollectData@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN11
	DD	imagerel $LN11+145
	DD	imagerel $unwind$?qt_static_metacall@CollectData@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?coleectDataNow@CollectData@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?coleectDataNow@CollectData@@QEAAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@CollectData@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@CollectData@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@CollectData@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@CollectData@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@CollectData@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@CollectData@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@CollectData@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	08217H
$unwind$?coleectDataNow@CollectData@@QEAAXXZ DD 010901H
	DD	04209H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@CollectData@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@CollectData@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'CollectData::staticMetaObject'', COMDAT
; File E:\MyProgram\EEG\MyEEGReader\EEGDataChart\EEGDataChart\x64\Debug\moc\moc_collectdata.cpp
; Line 89
	mov	rax, QWORD PTR __imp_?staticMetaObject@QThread@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@CollectData@@2UQMetaObject@@B, rax
; Line 90
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_CollectData@@3Uqt_meta_stringdata_CollectData_t@@B
	mov	QWORD PTR ?staticMetaObject@CollectData@@2UQMetaObject@@B+8, rax
; Line 91
	lea	rax, OFFSET FLAT:?qt_meta_data_CollectData@@3QBIB
	mov	QWORD PTR ?staticMetaObject@CollectData@@2UQMetaObject@@B+16, rax
; Line 92
	lea	rax, OFFSET FLAT:?qt_static_metacall@CollectData@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CollectData::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@CollectData@@2UQMetaObject@@B+24, rax
; Line 93
	mov	QWORD PTR ?staticMetaObject@CollectData@@2UQMetaObject@@B+32, 0
; Line 94
	mov	QWORD PTR ?staticMetaObject@CollectData@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@CollectData@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'CollectData::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?coleectDataNow@CollectData@@QEAAXXZ PROC		; CollectData::coleectDataNow
; File E:\MyProgram\EEG\MyEEGReader\EEGDataChart\EEGDataChart\x64\Debug\moc\moc_collectdata.cpp
; Line 130
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 131
	xor	r9d, r9d
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@CollectData@@2UQMetaObject@@B ; CollectData::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 132
	add	rsp, 40					; 00000028H
	ret	0
?coleectDataNow@CollectData@@QEAAXXZ ENDP		; CollectData::coleectDataNow
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
result$2 = 48
_o$ = 80
_c$ = 88
_id$ = 96
_a$ = 104
?qt_static_metacall@CollectData@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; CollectData::qt_static_metacall
; File E:\MyProgram\EEG\MyEEGReader\EEGDataChart\EEGDataChart\x64\Debug\moc\moc_collectdata.cpp
; Line 67
$LN11:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 68
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 69
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 71
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	jmp	SHORT $LN7@qt_static_
$LN6@qt_static_:
; Line 72
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?coleectDataNow@CollectData@@QEAAXXZ	; CollectData::coleectDataNow
$LN7@qt_static_:
; Line 75
	jmp	SHORT $LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	SHORT $LN8@qt_static_
; Line 76
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$2[rsp], rax
; Line 79
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	lea	rcx, OFFSET FLAT:?coleectDataNow@CollectData@@QEAAXXZ ; CollectData::coleectDataNow
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN9@qt_static_
; Line 80
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 0
$LN9@qt_static_:
$LN8@qt_static_:
$LN5@qt_static_:
; Line 86
	add	rsp, 72					; 00000048H
	ret	0
?qt_static_metacall@CollectData@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; CollectData::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@CollectData@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; CollectData::qt_metacall
; File E:\MyProgram\EEG\MyEEGReader\EEGDataChart\EEGDataChart\x64\Debug\moc\moc_collectdata.cpp
; Line 112
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 113
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QThread@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 114
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 115
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 116
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 117
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN5@qt_metacal
; Line 118
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@CollectData@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; CollectData::qt_static_metacall
$LN5@qt_metacal:
; Line 119
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 120
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 121
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN7@qt_metacal
; Line 122
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 123
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 125
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 126
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@CollectData@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; CollectData::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@CollectData@@UEAAPEAXPEBD@Z PROC		; CollectData::qt_metacast
; File E:\MyProgram\EEG\MyEEGReader\EEGDataChart\EEGDataChart\x64\Debug\moc\moc_collectdata.cpp
; Line 104
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 105
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 106
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_CollectData@@3Uqt_meta_stringdata_CollectData_t@@B+72
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 107
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 108
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QThread@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 109
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@CollectData@@UEAAPEAXPEBD@Z ENDP		; CollectData::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@CollectData@@UEBAPEBUQMetaObject@@XZ PROC	; CollectData::metaObject
; File E:\MyProgram\EEG\MyEEGReader\EEGDataChart\EEGDataChart\x64\Debug\moc\moc_collectdata.cpp
; Line 99
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 100
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@CollectData@@2UQMetaObject@@B ; CollectData::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 101
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@CollectData@@UEBAPEBUQMetaObject@@XZ ENDP	; CollectData::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\Qt\Qt5.13.0\5.13.0\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File E:\MyProgram\EEG\MyEEGReader\EEGDataChart\EEGDataChart\x64\Debug\moc\moc_collectdata.cpp
; Line 135
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File E:\MyProgram\EEG\MyEEGReader\EEGDataChart\EEGDataChart\x64\Debug\moc\moc_collectdata.cpp
; Line 135
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
